### ISSUE TITLE
Verify size data

### ISSUE THREAD

**Issue by dy** [thoughtspile/awesome-tiny-js#9]
It seems readme misinforms about some library sizes.
For example:
* _million_ is promoted as under 2kb, but it's ![npm bundle size](https://img.shields.io/bundlephobia/minzip/million)
* _redom_ is promoted as around 2kb, but it's ![npm bundle size](https://img.shields.io/bundlephobia/minzip/redom)
etc...

I'd suggest using live-size badges from [shields.io/size](https://shields.io/category/size).

**Comment by thoughtspile** [comment]
OK great idea. Even well-intended numbers go stale pretty easily as the library evolves. [Check out my attempt at badges](https://github.com/thoughtspile/awesome-tiny-js/blob/49c8fdf4dfa6cca843cf77099f9fbfba542c9da8/readme.md)

A few points:
- Standalone lib gzip overestimates the actual size increase, because library code gzips better together with app code (up to 2–3x in practice), and gzip also has fixed overhead. Based on the list and my own measurements (adding a library to a sizable app), I'd say 100–200b overestimation is usual.
- Some libraries (e.g. nanostores) report tree-shaken size — bundlephobia can't measure that. Bundlejs isn't very reliable either, filed an [issue](https://github.com/okikio/bundlejs/issues/51)
- Not sure what to do about massively tree-shakable libraries like date-fns or remeda, where the total bundle size makes no sense — I'll probably link to bundlephobia page that has "export analysis".

**Comment by thoughtspile** [comment]
> I'd possibly suggest changing style to smaller

Seems like only 24/25 px more or less aligns baseline with the default body font. Judging by lowercase k, the font size in the badge is also similar (it's subpixel territory, so YMMV)

> white or blue, to keep it similar to what there is now:

I went with gray as it's not too striking in either light or dark mode, looks like there's not much you can do beyond that.

Cool, I'll merge then

**Comment by thoughtspile** [comment]
See #10
